version: '3'
services:
    web:
        environment:
          - VIRTUAL_HOST=example.test.com
        image: nginx:latest
        volumes:
            - ./app:/home/wwwroot/
            - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf

    php:
        image: php:7.0-fpm
        volumes:
            - ./app:/home/wwwroot/

networks:
  default:
    external:
      name: nginx-proxy